[package]
name = "rospeek-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.41"
rayon = "1.10.0"
regex = "1.11.1"
serde_json = "1.0.142"
shellexpand = "3.1.1"
thiserror = "2.0.12"
